### ISSUE TITLE
是否更新到官方最新版

### ISSUE THREAD

**Issue by drzzm32** [NSDN/DiscuzMobile#1]
是否要跟随官方插件进行更新。
目前官方最新为1.4.7

**Comment by oxyflour** [comment]
http://addon.discuz.com/?@mobile.plugin
新版本只支持 x2.5 以上的（喵玉还在用 x2

**Comment by oxyflour** [comment]
@drzzm32 请测试这个分支 dz3v147

对每一个 bug 请开一个 issue，同时加上 dz3 标签

**Comment by oxyflour** [comment]
closed by
https://github.com/NSDN/DiscuzMobile/commit/6a262c5cfd5866fb2548edf92e840f87896ea0e5
