### ISSUE TITLE
帖子一楼内容为空

### ISSUE THREAD

**Issue by drzzm32** [NSDN/DiscuzMobile#3]
显示为null。其他楼层正常

**Comment by oxyflour** [comment]
discuz 很神奇地用了字符串来表示 true/false，真是让人始料未及呢
https://github.com/NSDN/DiscuzMobile/blob/43b7498abd24161246e70e70bdf6b4c7e34fae7e/source/plugin/mobile/api/1/viewthread.php#L43

本来下面那段 patch 是用来修复之前显示付费帖子的问题，现在看起来在新版本里面已经修复，所以 revert 掉就可以了
